<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Next_svg_1hpV4c</name>
   <tag></tag>
   <elementGuidId>484d5e52-197a-4844-97ef-a640ebf40610</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::*[name()='svg'][1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>svg.svg_1hpV4c</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tooltip[name=&quot;Welcome to your workspace From here, you can invite others to the workspace, view their activity, manage permissions, and easily switch between your workspaces. Next&quot;i] >> internal:role=button >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>70df63de-3624-4a82-8b3e-78add7128b25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>4ec00f46-6fe9-42c7-96ab-a69c0308fd9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>2fcf5279-a6f5-4747-934b-33dd6c74a47e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>8e246dce-3b7a-48d9-a891-0bc00b7de98f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>svg_1hpV4c</value>
      <webElementGuid>2aef17d4-ac9d-4e91-be76-a381c963804c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ee59eeae-342c-4f1c-904d-190f42a5fa42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa-tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>2c6ac210-47f9-4ac7-bccf-4eb5bb7b36b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;promoRouter&quot;)/div[@class=&quot;hint_1FsR5d hint_variant_dark_3fLXd3 hint_size_big_3goGbY hintUI_3Imo5a hint-place-right&quot;]/div[@class=&quot;hint__content_1Kxd5Y&quot;]/button[@class=&quot;hintUI__close_2JNv7h&quot;]/svg[@class=&quot;svg_1hpV4c&quot;]</value>
      <webElementGuid>d667d7a9-c4bb-4fba-bd46-8c8d792f7504</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>ed7f4895-bd19-4349-b8e8-6131ac53368b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome to your workspace'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>7a077ce8-3829-46b3-9053-933d4ed7acb7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
