analytics.onpremise.enable=true
analytics.integration.enable=true
analytics.project="{\\n  \\"id\\"\: 2243733,\\n  \\"name\\"\: \\"First Project\\",\\n  \\"teamId\\"\: 2223193,\\n  \\"organizationId\\"\: 2280027,\\n  \\"isSampleProject\\"\: false,\\n  \\"canAutoIntegrate\\"\: false\\n}"
analytics.team="{\\n  \\"id\\"\: 2223193\\n}"
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
analytics.testcloud.hub.switchHub.enable=true
onpremise.email="quangcuber002@gmail.com"
onpremise.password="K5koAvXt0fTTAD50ZVCwqQ\=\="
analytics.onpremise.organization="{\\"accountId\\"\:1527932,\\"accountUuid\\"\:\\"57fb0647-118d-491a-aaf0-365beef014c9\\",\\"id\\"\:2280027,\\"name\\"\:\\"My Organization_01\\",\\"role\\"\:\\"OWNER\\",\\"samlSSO\\"\:false,\\"kreLicense\\"\:false,\\"strictDomain\\"\:false}"
analytics.onpremise.server="https\://testops.katalon.io"
