<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Racket</name>
   <tag></tag>
   <elementGuidId>6613a1ea-c769-4f95-a824-161114305e41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.text-large:nth-child(3) button.transform-gpu.rounded-medium.bg-primary.appearance-none.subpixel-antialiased.font-semibold.whitespace-nowrap.motion-reduce\:transition-none.text-white.transition-transform-colors-opacity.cursor-pointer.select-none.text-small.tap-highlight-transparent.outline-solid.outline-transparent.inline-flex.justify-center.w-full[type=&quot;button&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type = 'button' and (text() = 'Racket' or . = 'Racket')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Racket&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>898bd085-70db-49cc-93e4-de0753408010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-0 group relative inline-flex items-center justify-center box-border appearance-none select-none whitespace-nowrap subpixel-antialiased overflow-hidden tap-highlight-transparent transform-gpu data-[pressed=true]:scale-[0.97] cursor-pointer outline-solid outline-transparent data-[focus-visible=true]:z-10 data-[focus-visible=true]:outline-2 data-[focus-visible=true]:outline-focus data-[focus-visible=true]:outline-offset-2 px-4 min-w-20 h-10 text-small gap-2 rounded-medium [&amp;>svg]:max-w-[theme(spacing.8)] transition-transform-colors-opacity motion-reduce:transition-none bg-primary data-[hover=true]:opacity-hover text-white font-semibold w-full</value>
      <webElementGuid>2a73ea39-5df3-4944-a06c-139391fcd3cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ab65fa18-dd82-424f-b964-bd48aadd90fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hover</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>668cb8f7-23bd-4eb1-8fca-6d6f31a9c1d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focus</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0c79405a-bcc1-4bae-bb34-a288cc2531ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Racket</value>
      <webElementGuid>6941a270-56dc-490f-8b53-df6a66a66388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' text-large ') and (position() = 3)]//button[@class and contains(concat(' ', normalize-space(@class), ' '), ' transform-gpu ') and contains(concat(' ', normalize-space(@class), ' '), ' rounded-medium ') and contains(concat(' ', normalize-space(@class), ' '), ' bg-primary ') and contains(concat(' ', normalize-space(@class), ' '), ' appearance-none ') and contains(concat(' ', normalize-space(@class), ' '), ' subpixel-antialiased ') and contains(concat(' ', normalize-space(@class), ' '), ' font-semibold ') and contains(concat(' ', normalize-space(@class), ' '), ' whitespace-nowrap ') and contains(concat(' ', normalize-space(@class), ' '), ' motion-reduce:transition-none ') and contains(concat(' ', normalize-space(@class), ' '), ' text-white ') and contains(concat(' ', normalize-space(@class), ' '), ' transition-transform-colors-opacity ') and contains(concat(' ', normalize-space(@class), ' '), ' cursor-pointer ') and contains(concat(' ', normalize-space(@class), ' '), ' select-none ') and contains(concat(' ', normalize-space(@class), ' '), ' text-small ') and contains(concat(' ', normalize-space(@class), ' '), ' tap-highlight-transparent ') and contains(concat(' ', normalize-space(@class), ' '), ' outline-solid ') and contains(concat(' ', normalize-space(@class), ' '), ' outline-transparent ') and contains(concat(' ', normalize-space(@class), ' '), ' inline-flex ') and contains(concat(' ', normalize-space(@class), ' '), ' justify-center ') and contains(concat(' ', normalize-space(@class), ' '), ' w-full ') and (@type = 'button')]</value>
      <webElementGuid>922bb3ff-4a8b-41de-b36d-02f44eea3ea5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>Racket</value>
      <webElementGuid>511e8c57-bf46-46a5-9acf-0318348235e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-3d11ab5e8f9e799d6b88bb05db596f49</value>
      <webElementGuid>324e88e6-11b0-41aa-bd55-2ecf86e19935</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' text-large ') and (position() = 3)]//button[@class and contains(concat(' ', normalize-space(@class), ' '), ' transform-gpu ') and contains(concat(' ', normalize-space(@class), ' '), ' rounded-medium ') and contains(concat(' ', normalize-space(@class), ' '), ' bg-primary ') and contains(concat(' ', normalize-space(@class), ' '), ' appearance-none ') and contains(concat(' ', normalize-space(@class), ' '), ' subpixel-antialiased ') and contains(concat(' ', normalize-space(@class), ' '), ' font-semibold ') and contains(concat(' ', normalize-space(@class), ' '), ' whitespace-nowrap ') and contains(concat(' ', normalize-space(@class), ' '), ' motion-reduce:transition-none ') and contains(concat(' ', normalize-space(@class), ' '), ' text-white ') and contains(concat(' ', normalize-space(@class), ' '), ' transition-transform-colors-opacity ') and contains(concat(' ', normalize-space(@class), ' '), ' cursor-pointer ') and contains(concat(' ', normalize-space(@class), ' '), ' select-none ') and contains(concat(' ', normalize-space(@class), ' '), ' text-small ') and contains(concat(' ', normalize-space(@class), ' '), ' tap-highlight-transparent ') and contains(concat(' ', normalize-space(@class), ' '), ' outline-solid ') and contains(concat(' ', normalize-space(@class), ' '), ' outline-transparent ') and contains(concat(' ', normalize-space(@class), ' '), ' inline-flex ') and contains(concat(' ', normalize-space(@class), ' '), ' justify-center ') and contains(concat(' ', normalize-space(@class), ' '), ' w-full ') and (@type = 'button')]</value>
      <webElementGuid>f5f4528a-3e7a-46ff-86ed-9a7752b4dbd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Racket' or . = 'Racket')]</value>
      <webElementGuid>c32bec67-c5a0-4f28-bfeb-efc79fe5ea35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(name() = 'li') and (position() = 2)]//button[@class and contains(concat(' ', normalize-space(@class), ' '), ' rounded-medium ') and contains(concat(' ', normalize-space(@class), ' '), ' transform-gpu ') and contains(concat(' ', normalize-space(@class), ' '), ' bg-primary ') and contains(concat(' ', normalize-space(@class), ' '), ' appearance-none ') and contains(concat(' ', normalize-space(@class), ' '), ' subpixel-antialiased ') and contains(concat(' ', normalize-space(@class), ' '), ' font-semibold ') and contains(concat(' ', normalize-space(@class), ' '), ' whitespace-nowrap ') and contains(concat(' ', normalize-space(@class), ' '), ' motion-reduce:transition-none ') and contains(concat(' ', normalize-space(@class), ' '), ' text-white ')]</value>
      <webElementGuid>9d240380-8d37-4d3b-9775-e2ea6badda97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[5]</value>
      <webElementGuid>05a4a65f-21bf-41a5-9a62-26275bafecc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/nav/header/ul[2]/li[2]/button</value>
      <webElementGuid>25ad0f0d-c2ae-45db-945b-f45f5e952d54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::button[1]</value>
      <webElementGuid>a03dceb2-a0cf-44ff-b741-af64f32e03f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BMB'])[1]/following::button[4]</value>
      <webElementGuid>f042bb42-547b-4a0c-b46e-b82a5939aadc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shuttlecock'])[1]/preceding::button[1]</value>
      <webElementGuid>985b89ee-3b7b-44af-8fdb-6aa41b1737e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shoes'])[1]/preceding::button[2]</value>
      <webElementGuid>ada0a8eb-639a-4781-89d8-aa2b4f0edf4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Racket']/parent::*</value>
      <webElementGuid>9d8c745b-3b12-4e3d-bc3f-6664dfce7dc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li[2]/button</value>
      <webElementGuid>5623d518-ca18-4106-803d-652db37c6332</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
