<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_About TI</name>
   <tag></tag>
   <elementGuidId>51d5f508-2885-49ad-9b01-b6dc399f3117</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-navtitle = 'header_aboutTI']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[data-navtitle=&quot;header_aboutTI&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=menuitem[name=&quot;About TI&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>654d346f-4437-47d6-8bb4-be53f1af5c29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>0762ed6c-937a-47f0-abb2-2aa8775b1847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>5176f45f-8f80-4352-a4b8-3ad0cd2a8fca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f3a484f0-5c99-4b67-936f-6a74e2a3e62d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ti_p-responsiveHeader-nav-bar-link js-responsiveHeader-nav-trigger</value>
      <webElementGuid>5978ebc2-7af1-450a-abad-7d209a7fb25c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nav-target</name>
      <type>Main</type>
      <value>responsiveHeader-panel-aboutTI</value>
      <webElementGuid>191e02fd-91aa-4ba7-9534-0b9f5ee936ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-navtitle</name>
      <type>Main</type>
      <value>header_aboutTI</value>
      <webElementGuid>8d9fba59-aaa2-459d-b8ce-86358eb03639</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-di-id</name>
      <type>Main</type>
      <value>di-id-266d57b8-110880b2</value>
      <webElementGuid>9ae44314-afaa-41a6-9c1b-85d71aa43f51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>About TI</value>
      <webElementGuid>f51b5b28-6257-4df0-ab53-9b262d5d1096</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>About TI</value>
      <webElementGuid>8ce6282f-4b7d-46a7-9bfd-141d1884a26d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-54c0d9ab12ee3b7419121236d12197e1</value>
      <webElementGuid>10ff02dc-6020-4d76-a1ee-1b8ebc43631a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-navtitle = 'header_aboutTI']</value>
      <webElementGuid>20e6594d-0270-464d-aeaf-3e30232b1a32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-navtitle = 'header_aboutTI']</value>
      <webElementGuid>e2e1155b-4af9-415d-9209-a01ee3008a1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'About TI' or . = 'About TI')]</value>
      <webElementGuid>4477b7b5-4492-4791-8735-03885b22862c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
