<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Design  development</name>
   <tag></tag>
   <elementGuidId>f776c9d9-26ae-4455-ac35-4606a1104870</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-navtitle = 'header_designresources']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[data-navtitle=&quot;header_designresources&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=menuitem[name=&quot;Design &amp; development&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2ffb5da8-0e23-4bd3-a7af-4a8101a5daff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>8cd49ed1-333d-4e11-b8fb-2c61f7a85158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>c74ab6ba-ce4c-4ae5-91af-6509c625aefd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>564a6386-9060-4445-9c67-841e5659d2e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ti_p-responsiveHeader-nav-bar-link js-responsiveHeader-nav-trigger</value>
      <webElementGuid>a9debc2c-8da8-4511-bf05-4f51b8c4b953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nav-target</name>
      <type>Main</type>
      <value>responsiveHeader-panel-designresources</value>
      <webElementGuid>923d171b-6509-4e67-8832-9a55e45d22a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-navtitle</name>
      <type>Main</type>
      <value>header_designresources</value>
      <webElementGuid>49da0f07-524e-4c04-9aad-ef5f74102f74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-di-id</name>
      <type>Main</type>
      <value>di-id-8e9c24d6-bd523851</value>
      <webElementGuid>72ce94a7-c93d-40df-9e1f-a650ab08f22d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Design &amp; development</value>
      <webElementGuid>7dc35b11-f38f-4246-9509-2450bdde8a93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>Design &amp; development</value>
      <webElementGuid>de4dd729-b4e1-4e78-9ddc-2a3a89bc2f6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-8dd380c4b2a74b1ed24ec1bf42881a89</value>
      <webElementGuid>3aef38ef-59ea-4c00-96a3-0fbf986f8d06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-navtitle = 'header_designresources']</value>
      <webElementGuid>5d0adfd6-dc34-4d6b-91ae-53e1c347b942</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-navtitle = 'header_designresources']</value>
      <webElementGuid>e2ed8a0a-d5f3-4e89-bfde-2be3bcba57b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Design &amp; development' or . = 'Design &amp; development')]</value>
      <webElementGuid>7a068b0b-a83e-4fc1-b971-643982d3994a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
