<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Ordering resources</name>
   <tag></tag>
   <elementGuidId>e2f73ef1-3429-4bc7-9dbf-f085910219e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-navtitle = 'header_ordering_resources']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[data-navtitle=&quot;header_ordering_resources&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=menuitem[name=&quot;Ordering resources&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0e3eb76a-9276-4d27-9d44-8374de475317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>f103af5a-5450-40ef-bd17-a38c0eb66ecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>638e9e45-365a-43be-bdc4-3185c6dc4256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0db97dba-fa1e-42a9-91f0-884451f42e18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ti_p-responsiveHeader-nav-bar-link js-responsiveHeader-nav-trigger</value>
      <webElementGuid>47617485-523a-44ec-831c-4b58caf320b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nav-target</name>
      <type>Main</type>
      <value>responsiveHeader-panel-orderingResources</value>
      <webElementGuid>09191099-add5-454e-b0ea-a85d86c5255b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-navtitle</name>
      <type>Main</type>
      <value>header_ordering_resources</value>
      <webElementGuid>f9c1d8a4-d463-4ea3-9c36-5ea491e38f92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-di-id</name>
      <type>Main</type>
      <value>di-id-2da15f85-5c7cafe3</value>
      <webElementGuid>405aa959-b3aa-4445-9795-25a6e43c1b03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ordering resources</value>
      <webElementGuid>364e6785-15da-4dfd-817f-924b124a2963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>Ordering resources</value>
      <webElementGuid>424759f5-badd-44d1-b6be-f896b4b22159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-11597f6be21cc979d0bed57d096e57c1</value>
      <webElementGuid>16b5458a-c811-47f9-b762-ec72379cae37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-navtitle = 'header_ordering_resources']</value>
      <webElementGuid>b9c76f91-31d5-4770-892d-e8952d3b9a36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-navtitle = 'header_ordering_resources']</value>
      <webElementGuid>0c59e60e-a87a-44f3-893b-ad39d2017731</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Ordering resources' or . = 'Ordering resources')]</value>
      <webElementGuid>754726df-e280-42ee-8431-921654770736</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
