<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Products</name>
   <tag></tag>
   <elementGuidId>73ea14c5-6ff9-4f7b-ad0a-5923ee346db4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-navtitle = 'header_products']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[data-navtitle=&quot;header_products&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=menuitem[name=&quot;Products&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3400f088-f48c-45ac-830f-9c6cc30ecff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>9ea4888d-b943-4f20-aaaa-85ed181efe13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>2d9893c4-2ceb-40ab-b98a-5af331f54247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8f9e6105-077c-40de-a6e1-4e29fb2ea756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ti_p-responsiveHeader-nav-bar-link js-responsiveHeader-nav-trigger</value>
      <webElementGuid>9de03c36-9f61-42e0-9c35-f45fccf6651a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nav-target</name>
      <type>Main</type>
      <value>responsiveHeader-panel-products</value>
      <webElementGuid>1b9db1ec-096a-4ccc-bdb7-a8f60c6359b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-navtitle</name>
      <type>Main</type>
      <value>header_products</value>
      <webElementGuid>b6ab19ef-be02-4391-a3ae-94bffadb2d4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-di-id</name>
      <type>Main</type>
      <value>di-id-266d57b8-2af3a17</value>
      <webElementGuid>bc896f76-5ee3-49a0-93fb-9265e18ec38c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Products</value>
      <webElementGuid>1ed54c4c-ab87-4109-b4b8-17a2be37662a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>Products</value>
      <webElementGuid>f8a0f44b-44f0-460f-bc5f-17df3b49a52f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-b5a4695f2405497878401e35cba227d1</value>
      <webElementGuid>7d2e93a8-2874-480e-b1fe-cbb8b5154872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-navtitle = 'header_products']</value>
      <webElementGuid>42925c2a-ef9c-40ad-aac2-57ce938a8315</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-navtitle = 'header_products']</value>
      <webElementGuid>f651eb4b-96a3-484d-8242-51bc40dc5529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Products' or . = 'Products')]</value>
      <webElementGuid>61e4b953-5aa8-4ae0-a833-fc35e643c419</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
