<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Quality  reliability</name>
   <tag></tag>
   <elementGuidId>6d9fe429-bbb4-466c-954a-d729f5e6ad89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-navtitle = 'header_qualityReliability']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[data-navtitle=&quot;header_qualityReliability&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=menuitem[name=&quot;Quality &amp; reliability&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a8ba0c79-ab92-42f1-af35-536be65a4e82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>ffa7ea3f-bbdd-466e-a04b-166f5c78e781</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>c8b6ea91-9b0f-4e67-b45b-553c7d138f2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b77586d2-aef9-490a-a168-444ccbd1c098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ti_p-responsiveHeader-nav-bar-link js-responsiveHeader-nav-trigger</value>
      <webElementGuid>6aeb0989-5f48-4d1a-852a-da81b53d0509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nav-target</name>
      <type>Main</type>
      <value>responsiveHeader-panel-qualityReliability</value>
      <webElementGuid>cdebfb31-e19a-459b-ab66-eea312aa6f55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-navtitle</name>
      <type>Main</type>
      <value>header_qualityReliability</value>
      <webElementGuid>5a4847b8-c6d2-46e9-9379-b2d6553d781b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-di-id</name>
      <type>Main</type>
      <value>di-id-8e9c24d6-beef94bc</value>
      <webElementGuid>c845ae23-bd91-4d33-a256-d0165036bbd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Quality &amp; reliability</value>
      <webElementGuid>4b6bda1b-7206-4dc9-8ec5-aca051cffc46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>Quality &amp; reliability</value>
      <webElementGuid>7e3b1abf-e57b-45b0-beab-3a01f4fae994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-ee391de641e03990861cf9db9a1186ca</value>
      <webElementGuid>5e689f99-50f7-4e1c-8f1f-63bc452dfadc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-navtitle = 'header_qualityReliability']</value>
      <webElementGuid>01a128b9-f231-4b76-b0f1-5729d040e924</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-navtitle = 'header_qualityReliability']</value>
      <webElementGuid>898fc175-b38c-42f5-a16a-23c06c4a6206</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Quality &amp; reliability' or . = 'Quality &amp; reliability')]</value>
      <webElementGuid>06c7006b-4ead-4613-bc7b-3c7082ffc82e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
