<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_error</name>
   <tag></tag>
   <elementGuidId>431add13-f428-481e-b99d-889f0225d998</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#error</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'error']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Authentication failed.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c028ef9f-aab9-485a-8857-7828bafaa75f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>error</value>
      <webElementGuid>25249004-4f8d-4c93-90e1-8ba63fc95a90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>error</value>
      <webElementGuid>a10f9172-6bd9-444a-841c-b7aea6560c5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>error</value>
      <webElementGuid>f32bed7e-62c4-408a-8310-135acec6c9d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>Authentication failed.</value>
      <webElementGuid>9cf8b00d-2e90-4b5a-9d43-5dfb73839009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-374ac306fe964c890742d8b5f65ab3f3</value>
      <webElementGuid>d32fb8e7-c256-4bf8-aaec-30404bafb97c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'error']</value>
      <webElementGuid>93dc6019-daeb-4de7-a738-d570fe6cea15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'error']</value>
      <webElementGuid>19743282-2f0b-46f5-8e32-68902eaa1fc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'error' and (text() = 'error' or . = 'error')]</value>
      <webElementGuid>1abe7104-251d-4ced-9d57-be78e91b6830</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
