<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_quangcuber002gmail.com_codeEntry-1</name>
   <tag></tag>
   <elementGuidId>b4b15d4a-2442-4140-8d46-7d1b7e6c7e4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#codeEntry-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='codeEntry-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Enter code digit 2&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5f1fc754-c376-471c-bbe7-d34029f91fcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>334761ca-20a5-4421-846b-3c358c589cab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>2b941c6f-359b-4970-ac0c-92d397b64776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>codeEntry-1</value>
      <webElementGuid>1e484952-06ca-4c8b-840b-f1855b2a8aaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Enter code digit 2</value>
      <webElementGuid>c6e924fd-139b-4646-b076-d2e0491e7c7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>c40059cc-32ba-4bfa-bce9-e7e3c71053fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>field-11__validationMessage</value>
      <webElementGuid>b17e5680-46fa-4743-aa0e-8c1986baed04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fui-Input__input r12stul0</value>
      <webElementGuid>14e35085-d316-4c71-9618-d323ba782ec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;codeEntry-1&quot;)</value>
      <webElementGuid>4a83b610-8095-431f-a504-606ae06855b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='codeEntry-1']</value>
      <webElementGuid>bc9fdab4-08ba-4fb0-a40c-1084f0010f67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='view']/div/div[3]/div/div/div[2]/span/input</value>
      <webElementGuid>85b2583c-ea97-40a8-b528-915716a473ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/input</value>
      <webElementGuid>bf4d1fe5-74ea-4ead-834f-c3b9e10aaca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'codeEntry-1']</value>
      <webElementGuid>f146dbc3-3ef4-40d2-b780-471ef2c181ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
