<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_quangcuber002gmail.com_codeEntry-2</name>
   <tag></tag>
   <elementGuidId>053ef119-9d3b-41bb-9b76-67e1ca5da4d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#codeEntry-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='codeEntry-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Enter code digit 3&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>390add58-aaa9-46d5-9147-9b3a39d40228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bdb45455-eeb9-4dc4-97f9-98d7c6bd0c24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>47ec8f6e-0da8-4873-8ebb-9e5830a0d7f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>codeEntry-2</value>
      <webElementGuid>6f6e2aea-5a95-4991-90e2-51c12d3a2d6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Enter code digit 3</value>
      <webElementGuid>a9e29118-0690-47a1-9c97-afd3107c0252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>9da88ff6-bbfd-4be0-87cc-c4ca74520892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>field-11__validationMessage</value>
      <webElementGuid>e7cd9a63-c3d3-43b8-88b1-1728deb937ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fui-Input__input r12stul0</value>
      <webElementGuid>ad9667c7-7b24-4da6-be63-040d4b6019e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;codeEntry-2&quot;)</value>
      <webElementGuid>69f8e170-7cfe-4ce9-b9d3-c1365921bda7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='codeEntry-2']</value>
      <webElementGuid>179175c3-b1ec-42de-b12d-8689caf137fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='view']/div/div[3]/div/div/div[3]/span/input</value>
      <webElementGuid>c14cae9c-d7ec-472a-a7de-e062f5a55565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span/input</value>
      <webElementGuid>e5123378-101b-40b8-874a-60b18276e912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'codeEntry-2']</value>
      <webElementGuid>cf88ee7a-3d6f-4655-aa2e-85e3c56477d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
