<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_quangcuber002gmail.com_codeEntry-3</name>
   <tag></tag>
   <elementGuidId>c4861140-c21f-4ed4-8842-0b405586b07d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#codeEntry-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='codeEntry-3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Enter code digit 4&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cc5c7621-e6fe-4cdf-8165-86deea813634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>787e82a4-01bf-48af-99c7-16d671e02917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>784c27d7-f191-4afe-a0b9-0b9e02bf5967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>codeEntry-3</value>
      <webElementGuid>4cde2d73-3911-4945-8c22-96f050bdb45f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Enter code digit 4</value>
      <webElementGuid>53e9ec5d-86cd-4c70-b8e6-1c5748cc0301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>7bd7dcd7-7f30-40d9-8ba4-8fed6fc717c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>field-11__validationMessage</value>
      <webElementGuid>80c44198-0d08-4984-b706-50b1f3b59c76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fui-Input__input r12stul0</value>
      <webElementGuid>a8ac8dbe-9bbd-44fd-8405-fea0d8daa9c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;codeEntry-3&quot;)</value>
      <webElementGuid>fa6a39f3-6b94-4ecc-9c3d-a891cb2d2f44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='codeEntry-3']</value>
      <webElementGuid>05debf0f-c584-409b-ac17-7dd104ed2a33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='view']/div/div[3]/div/div/div[4]/span/input</value>
      <webElementGuid>1ba03cda-80f7-4a42-b7fa-3dc14d388a7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/span/input</value>
      <webElementGuid>87bc1539-ebbe-4e8f-960f-68556737db99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'codeEntry-3']</value>
      <webElementGuid>ad6d8570-5de6-4749-a3d0-8d48a62879a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
