<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_quangcuber002gmail.com_codeEntry-4</name>
   <tag></tag>
   <elementGuidId>9f0682c9-d453-45b8-beee-3dd1d9a3549b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#codeEntry-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='codeEntry-4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Enter code digit 5&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aac050bc-63ca-44fb-922e-7d6aaed181a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>18eb556a-ea9b-4731-85dc-9250b8d32884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>eeac5697-bebe-4896-8311-100c4302a6dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>codeEntry-4</value>
      <webElementGuid>23b6d1be-8bc5-4029-b719-85c1dfeb5737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Enter code digit 5</value>
      <webElementGuid>b48cf59a-38c2-4ebf-a8e6-876b890b5d35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>88c80404-da93-470b-83a9-cc72c30067b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>field-11__validationMessage</value>
      <webElementGuid>0cfdfb33-130f-4267-9631-3da6157bf620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fui-Input__input r12stul0</value>
      <webElementGuid>ab92bcec-4370-4bb7-8f57-51e8973c1ccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;codeEntry-4&quot;)</value>
      <webElementGuid>4e8e52bb-c991-41ed-91fa-63f3bdb47983</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='codeEntry-4']</value>
      <webElementGuid>a8a1a02a-1796-4428-aeb9-6b45e1efd84d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='view']/div/div[3]/div/div/div[5]/span/input</value>
      <webElementGuid>3ffc690e-c8ab-4140-a00c-5a7e5ce0c38c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/span/input</value>
      <webElementGuid>9df439ad-510b-4744-a043-2f3d9ceefe5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'codeEntry-4']</value>
      <webElementGuid>69fe5793-833a-4bb7-94f7-dde58c0397ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
