<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_quangcuber002gmail.com_codeEntry-0</name>
   <tag></tag>
   <elementGuidId>9e6252e5-46c1-4313-ab6c-34a1ff532291</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#codeEntry-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='codeEntry-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Enter code digit 1&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f536f0ea-05f4-42cb-9f53-ebe91f8db5df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>310e925b-3d90-4f5b-8b37-22ce7493db6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7d8d1a71-8fc4-4626-bc4e-7e3c621089fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>codeEntry-0</value>
      <webElementGuid>9c8fba62-64bc-41cb-ade3-10e7e521dae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Enter code digit 1</value>
      <webElementGuid>e20d9968-7ab2-4cb7-8f4f-bce96ad57182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>7f2638f0-29c4-45a8-8572-7c490192debc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>field-11__validationMessage</value>
      <webElementGuid>dd946a1f-3b69-4541-b0d1-71bed7e31005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fui-Input__input r12stul0</value>
      <webElementGuid>b94e3991-6fcd-4451-8a19-906248337756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;codeEntry-0&quot;)</value>
      <webElementGuid>decf79ba-f250-45c7-9064-fb51eaa430d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='codeEntry-0']</value>
      <webElementGuid>403eb702-9c06-4b8e-9956-bb099e2673c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='view']/div/div[3]/div/div/div/span/input</value>
      <webElementGuid>2adaab71-f8ca-4a25-a627-0270fc0a92ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>43630974-c6ca-49bd-813d-7412e3e50ebb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'codeEntry-0']</value>
      <webElementGuid>993b0c01-1e44-45d7-a5f9-8fc4a5a5a19d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
