<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_pjAcceptCookieBarBtn</name>
   <tag></tag>
   <elementGuidId>7f53fb55-2235-44aa-92f1-05a2238e3c84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'pjAcceptCookieBarBtn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pjAcceptCookieBarBtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;I Agree&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3b0d88ff-4b97-4541-9a9b-122bb3326368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pjAcceptCookieBarBtn</value>
      <webElementGuid>18463bb8-a4ab-44b8-aa02-de40a79bf181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d6ebd391-8734-47cb-b04a-0d473b513b35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pjAcceptCookieBarBtn</value>
      <webElementGuid>7fb3586a-e467-4172-baae-1fdcdb0b3ef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1f96fcb1-b201-4697-8a30-357d0c2a440f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>pjAcceptCookieBarBtn</value>
      <webElementGuid>88120c7e-1a56-4459-8095-a9219658a254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>I Agree</value>
      <webElementGuid>1e4f13b9-c98c-4715-ada1-edccb86f8058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-e5a099c37b664f89b12c36e382994cff</value>
      <webElementGuid>779a1d2e-6672-49c5-8419-cb1c6306b0bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'pjAcceptCookieBarBtn']</value>
      <webElementGuid>672910c0-a9b8-498d-a757-ca187140bc66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'pjAcceptCookieBarBtn']</value>
      <webElementGuid>319dd55e-8c6e-4c02-a7d4-71c0fc572f0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'pjAcceptCookieBarBtn' and @type = 'button' and (text() = 'pjAcceptCookieBarBtn' or . = 'pjAcceptCookieBarBtn')]</value>
      <webElementGuid>bc9f0cc7-d429-4406-8cae-fcdcb5f92990</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
