<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_msg</name>
   <tag></tag>
   <elementGuidId>f285d0e8-08ee-4a39-a93f-2ea8b458940c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'msg']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#msg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;The credentials you provided cannot be determined to be authentic.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>182d4bfe-4aee-4bb5-9d45-2d1708422362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>msg</value>
      <webElementGuid>757c9ac6-15e6-45e5-88ab-46df4f04325f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>errors</value>
      <webElementGuid>f52c3498-cf64-4f5a-84c3-465b0018090e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>msg</value>
      <webElementGuid>2c386cef-3e78-4a6f-84bf-ff57139cbf66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>The credentials you provided cannot be determined to be authentic.</value>
      <webElementGuid>53112b38-5e49-4b53-8477-8bffb9631518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-143e2805aa3c9c208d8b5fd051d49fb7</value>
      <webElementGuid>10600644-e19e-46b9-b462-97533a7ca95a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'msg']</value>
      <webElementGuid>c8e90679-052a-40af-8f91-2591ef4cc21a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'msg']</value>
      <webElementGuid>0c1b114c-fd9a-44ef-9559-5131fb72307e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'msg' and (text() = 'msg' or . = 'msg')]</value>
      <webElementGuid>87543b05-0f50-4dd4-bf15-3d6eb045237e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
