<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_The credentials you provided cannot be _f95d95</name>
   <tag></tag>
   <elementGuidId>b950a07d-9314-4a49-9acf-76d8554c488a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#msg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='msg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;The credentials you provided cannot be determined to be authentic.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4c9f4777-8c78-4fd3-a534-b157e1e1f185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>msg</value>
      <webElementGuid>ea45d02c-e881-43cc-a266-a5b2b8fe1c4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>errors</value>
      <webElementGuid>9d8185d0-426d-4e75-827e-8a878ab886a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The credentials you provided cannot be determined to be authentic.</value>
      <webElementGuid>b284e3b9-74a3-47ce-ab58-44f024a9371b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;msg&quot;)</value>
      <webElementGuid>ca990559-3509-4e1e-b0de-4d2adebc806e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='msg']</value>
      <webElementGuid>a4203b01-7bb8-4036-b8cc-ceacb926d00e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='fm1']/div</value>
      <webElementGuid>e9b9c801-30e4-4594-8205-808a7bd98713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Central Authentication Service'])[1]/following::div[3]</value>
      <webElementGuid>fd8495c6-9b19-4916-b93a-6d8e352b38ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter your Username and Password'])[1]/preceding::div[1]</value>
      <webElementGuid>d7cfd5af-9cde-44d3-ac5b-1d23a8d728f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='The credentials you provided cannot be determined to be authentic.']/parent::*</value>
      <webElementGuid>bab679ff-fff0-4d8e-8aad-56cf5db6d24d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div</value>
      <webElementGuid>e102d574-b3cc-4fec-af87-55e6dbc0b52d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'msg' and (text() = 'The credentials you provided cannot be determined to be authentic.' or . = 'The credentials you provided cannot be determined to be authentic.')]</value>
      <webElementGuid>1256fde2-3cac-46ec-8bbc-94262e452453</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
