<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nextjs-portal_nextjs-portal-ext App-d3f</name>
   <tag></tag>
   <elementGuidId>2120b926-dae2-44a3-b6ff-0e7b6ee9e8f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//nextjs-portal</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>nextjs-portal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>nextjs-portal</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>nextjs-portal</value>
      <webElementGuid>0a7e26b4-aed8-4be4-9f61-13e0f31fe31f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>nextjs-portal</value>
      <webElementGuid>db22ee22-043a-4a2c-8475-0b957f6d40dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-6de2b2cc8f5cd6aa3c2c56bcba237538</value>
      <webElementGuid>dddbad42-bc48-44e6-9eed-f9d20bf445ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//nextjs-portal</value>
      <webElementGuid>5660ea8d-4c06-44ce-972f-5502911ed2e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//nextjs-portal</value>
      <webElementGuid>3b919cb5-93c8-4b24-859b-b4da46231052</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//nextjs-portal[(text() = 'nextjs-portal' or . = 'nextjs-portal')]</value>
      <webElementGuid>24550684-8955-4279-91ff-bc54b1937268</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
