<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Finish editing the document</name>
   <tag></tag>
   <elementGuidId>70e5b4a6-0dd4-4427-b47e-f75b065d3048</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-type = 'main_done_button']//*[@aria-label = 'Finish editing the document']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[data-type=&quot;main_done_button&quot;] [aria-label=&quot;Finish\ editing\ the\ document&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test=&quot;topHeaderTools&quot;] >> internal:label=&quot;Finish editing the document&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>85aaf778-4ea4-4080-8bf1-ae5b6ad0b695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mHW8g _1843e Y_2gK _1UobI _2otej _6l-6h dbu86</value>
      <webElementGuid>125522b6-92a1-4009-812e-ed153366a889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Finish editing the document</value>
      <webElementGuid>fad6ca68-fb30-4fc1-a42b-1ce055164a17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-busy</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ce691785-24bf-419a-aa1f-5feb35f74ef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-pressed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>43a5ca4c-f13e-4198-b256-29121d89a9d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6322c97f-c716-4176-b9b0-4eb2abbe4e1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Finish editing the document</value>
      <webElementGuid>405fbafd-096e-4231-96f6-b1017c6714de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>DONE</value>
      <webElementGuid>2285d1fd-0e03-43e7-a121-966703123707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-a5dbee985bd6180c6b9077df566ee46d</value>
      <webElementGuid>daf68f10-bd3e-460f-ae84-db3352a786a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-type = 'main_done_button']//*[@aria-label = 'Finish editing the document']</value>
      <webElementGuid>72ddc73a-b005-408a-986c-710c83bf7d81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-type = 'main_done_button']//*[@aria-label = 'Finish editing the document']</value>
      <webElementGuid>0ee0c039-38ca-4c37-b76c-4066939a915a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Finish editing the document' or . = 'Finish editing the document')]</value>
      <webElementGuid>57c29cc3-6a4c-4ff5-adfd-7e25904c3010</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
