<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1-2</name>
   <tag></tag>
   <elementGuidId>4c4cd470-20a9-424a-aecb-32c12ced0e7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@aria-labelledby = '1-2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[aria-labelledby=&quot;\31 -2&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Add a signature&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3cde7a1e-c2eb-499d-97de-6ca8fc6f37de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fillable-field--1-2</value>
      <webElementGuid>9ede4358-168d-4b41-8077-d7818fb8f94b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>1-2</value>
      <webElementGuid>75a49bee-1a72-4776-a263-1597b86aaa39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>1041c13f-ca7f-46a8-b895-68b8dd8534e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>signTool-SignTool elementHover-Content</value>
      <webElementGuid>0981b0ec-bb31-4e09-a84a-a83a158571b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>d46a2b51-76b4-4476-972a-45721198c555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focuscontrollerinterceptfocus</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>57c7411f-a761-4ac4-a89d-bfb8a9d85f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1-2</value>
      <webElementGuid>1c846bf0-2d6f-4a8b-b067-b72f7e83bc44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>Signature</value>
      <webElementGuid>cca1a4cc-1584-428f-a2d0-8a85946824ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-ca0c98126e9f4396e95621fbab52e742</value>
      <webElementGuid>4781eec0-a919-4419-9ba8-0bacf41a05c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-labelledby = '1-2']</value>
      <webElementGuid>bb7386e9-998e-4345-a324-a6dc386ec890</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-labelledby = '1-2']</value>
      <webElementGuid>bcabcae8-a7f5-4d65-8585-34ecfd5789bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'fillable-field--1-2' and (text() = '1-2' or . = '1-2')]</value>
      <webElementGuid>e90165d7-3ea2-46c3-8ec1-00456642e835</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
