<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_ng nhp_hplogo</name>
   <tag></tag>
   <elementGuidId>8d2ea641-41df-4fdb-b669-e6316cc32652</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='hplogo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#hplogo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Môn trượt ván trên tuyết năm 2026&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bdadbeb3-b7e1-45bf-b16c-fcf24b496b13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lnXdpd</value>
      <webElementGuid>4781b132-8d07-409b-8b7f-06d84983d45b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Môn trượt ván trên tuyết năm 2026</value>
      <webElementGuid>fdea9b11-3c11-43d2-bb59-c188cf2d16f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>1b0e9c25-81ef-4470-9d39-36cebaf93927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/logos/doodles/2026/snowboarding-2026-feb-12-o-6753651837111047-law.gif</value>
      <webElementGuid>09c3fe9d-351b-44fd-90a1-6bca3b635492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Môn trượt ván trên tuyết năm 2026</value>
      <webElementGuid>db7491db-33ad-4a79-a8cd-62b9290957b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>7157e773-1fd2-4c1d-852d-e833b2e957ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hplogo</value>
      <webElementGuid>4575823f-34b4-4a18-8589-5781208fda3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csiid</name>
      <type>Main</type>
      <value>oZGNafn4DN7S2roP7-qNqQU_1</value>
      <webElementGuid>886b6a16-21c8-42f2-941f-47c981336fd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-atf</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>4c902bf3-491c-42ad-9ab2-79df6323a21e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hplogo&quot;)</value>
      <webElementGuid>3ce3d964-9eb2-497e-acfa-865599996483</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='hplogo']</value>
      <webElementGuid>635ae3ec-d723-45ee-9e28-d822232ae9a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='LS8OJ']/div/a/picture/img</value>
      <webElementGuid>0aa6738f-ab1d-460b-9647-115c3220865f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Môn trượt ván trên tuyết năm 2026']</value>
      <webElementGuid>944d968b-fcd4-4906-a834-ee9a72a8ecaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>9711ea33-458d-4c28-a198-a02a4791fb39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Môn trượt ván trên tuyết năm 2026' and @src = '/logos/doodles/2026/snowboarding-2026-feb-12-o-6753651837111047-law.gif' and @title = 'Môn trượt ván trên tuyết năm 2026' and @id = 'hplogo']</value>
      <webElementGuid>0ee45cb3-8da7-4988-a162-36e64ad8aa0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
