<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Brand_font-inherit text-100 leading-1_131126</name>
   <tag></tag>
   <elementGuidId>14669689-bf22-4b1e-a0dc-05f7f068022c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Lining&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dbf3bd02-b7ba-44c5-ba74-84f7e4728632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Lining</value>
      <webElementGuid>a6da9432-52ad-4d89-8676-13129244a97d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>:r1i:</value>
      <webElementGuid>e0b7140c-3de3-4860-8816-99d9407bcf4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>04b72d7f-44ae-462d-9616-c84398f000ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2eefe47f-c957-4991-82e0-018bdbd302a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-inherit text-[100%] leading-[1.15] m-0 p-0 overflow-visible box-border absolute top-0 w-full h-full opacity-[0.0001] z-[1] cursor-pointer disabled:cursor-default</value>
      <webElementGuid>35644d3a-1421-41c6-9ff9-210e66d891ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;__variable_4bc053 font-sans&quot;]/div[@class=&quot;relative flex flex-col min-h-screen&quot;]/main[@class=&quot;flex justify-center py-10 h-full flex-grow overflow-auto&quot;]/section[@class=&quot;flex flex-col items-start&quot;]/main[1]/div[@class=&quot;flex flex-col gap-4&quot;]/div[@class=&quot;flex&quot;]/div[@class=&quot;hidden xl:block lg:block md:block sm:hidden&quot;]/div[@class=&quot;flex-col items-center px-4&quot;]/section[@class=&quot;w-[80%] flex flex-col items-start pb-3&quot;]/label[@class=&quot;group relative max-w-fit inline-flex items-center justify-start cursor-pointer tap-highlight-transparent p-2 -m-2 select-none&quot;]/input[@class=&quot;font-inherit text-[100%] leading-[1.15] m-0 p-0 overflow-visible box-border absolute top-0 w-full h-full opacity-[0.0001] z-[1] cursor-pointer disabled:cursor-default&quot;]</value>
      <webElementGuid>4cfa2567-48d2-4452-9ca8-0e935254acfb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[2]</value>
      <webElementGuid>3c8eb510-f9a1-49d1-a8a6-68ebed33c4d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/section/main/div/div[2]/div/div/section/label/input</value>
      <webElementGuid>6a05940d-a2a3-49d4-8580-8383a41dcb82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>6d3c735b-98a9-4176-8a5e-8a05166c520a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>632ff07a-f275-49e3-95c1-1d3a5c25c77a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
