<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_icon-login</name>
   <tag></tag>
   <elementGuidId>fdd332b5-35c0-4c3c-84ba-020c1e15ce1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.icon-login</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' icon-login ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>app-sign-in a</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>99d475e6-ec28-4fc8-b478-9775c7b07c7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-login</value>
      <webElementGuid>15ebba5c-bbbf-4ff9-850d-20f14952098e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>icon-login</value>
      <webElementGuid>02acefa9-a3e1-448f-83c3-28f9707bd0e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-cb099d98b09544b3dfe7eefb0baf990f</value>
      <webElementGuid>f7c22d97-5a55-4aa8-b419-0414667d4f73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' icon-login ')]</value>
      <webElementGuid>b88b2301-5aad-4573-8203-df604087bb3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' icon-login ')]</value>
      <webElementGuid>0a04f931-60d1-482f-9d10-f0ae72afdb63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = 'icon-login' or . = 'icon-login')]</value>
      <webElementGuid>bcf43814-e4c4-48dc-975f-bf4be1f7b7ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
