<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_random_data.txt</name>
   <tag></tag>
   <elementGuidId>d4cc5820-a19f-4883-bf98-678ece4d8b89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[href=&quot;download\/random_data\.txt&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@href = 'download/random_data.txt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;random_data.txt&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>031e8043-3147-497a-9acc-7d311a906667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>download/random_data.txt</value>
      <webElementGuid>6eb89566-febe-45a9-bbad-b645855848ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>random_data.txt</value>
      <webElementGuid>bcfce1d2-6065-4c62-b716-83246b92f082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>random_data.txt</value>
      <webElementGuid>27eed6dd-fbfc-4d86-ab1d-e9f56064a127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-18021ea310fdb72cf8582b8b98aedf78</value>
      <webElementGuid>bed06738-7b01-4ac5-b372-7894b745503f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@href = 'download/random_data.txt']</value>
      <webElementGuid>d299e210-8838-4bcd-bfc0-417e6f2f3605</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@href = 'download/random_data.txt']</value>
      <webElementGuid>9502b97b-0575-4968-b121-8ba7ceaa84b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'download/random_data.txt' and (text() = 'random_data.txt' or . = 'random_data.txt')]</value>
      <webElementGuid>e2d23ff5-72c8-431c-bba3-7b3cb3b88de7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
