<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_98128</name>
   <tag></tag>
   <elementGuidId>c0feb8db-cf0a-4446-8896-e4956970c1d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div[5]/table/tbody/tr[2]/td[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(6)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;98128&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>c552fb36-de98-4d76-a2ad-7b26bdbfd39c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>98128</value>
      <webElementGuid>d0c98b37-d90e-4768-9ced-b557025eb5f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;w3-responsive&quot;]/table[@class=&quot;ws-table-all notranslate&quot;]/tbody[1]/tr[2]/td[6]</value>
      <webElementGuid>436ee3cd-6e09-43ea-a28c-e7748bcf7f77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div[5]/table/tbody/tr[2]/td[6]</value>
      <webElementGuid>f7b8ba8d-3a13-4d28-abcf-1f70031a4cd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seattle'])[1]/following::td[1]</value>
      <webElementGuid>ec047f34-9f21-4c98-9f4a-d44deafaa186</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Karl Jablonski'])[1]/following::td[3]</value>
      <webElementGuid>9cf0f403-21fe-49d5-8a88-25b2d8bc51cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='USA'])[1]/preceding::td[1]</value>
      <webElementGuid>d1e2c8b9-33b9-4e6a-85fb-477d99c4487e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wilman Kala'])[1]/preceding::td[3]</value>
      <webElementGuid>4518d254-7ec7-4cbf-93e8-3e9fa26eff41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='98128']/parent::*</value>
      <webElementGuid>72cdc8f4-8cba-4fe0-bfc1-34d31be671eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]</value>
      <webElementGuid>aa27b23c-c38c-4a62-98fb-43185a9fd1d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '98128' or . = '98128')]</value>
      <webElementGuid>b4f6327d-9118-4108-b26b-7f80e1067973</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
