<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Yonex</name>
   <tag></tag>
   <elementGuidId>7ac93876-928f-4a30-9a41-7972ebcaca55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@aria-labelledby = ':r1j:']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[aria-labelledby=&quot;\:r1j\:&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Yonex&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1865effb-7bf6-49bd-9c4f-32b7e80d9261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Yonex</value>
      <webElementGuid>24d2e679-710a-4a40-80fe-3b820b82a195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>:r1j:</value>
      <webElementGuid>5713da3c-019e-46a9-b502-19d185a96529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>51245c2d-12c3-46c4-8edf-1dcef619e7ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5e47435b-de0b-43ff-a3e0-ddc2f89afcfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-inherit text-[100%] leading-[1.15] m-0 p-0 overflow-visible box-border absolute top-0 w-full h-full opacity-[0.0001] z-[1] cursor-pointer disabled:cursor-default</value>
      <webElementGuid>a1ebee3e-bf3b-4a9d-8ca9-a4a9d7e999f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yonex</value>
      <webElementGuid>48d95c80-f041-44ba-a412-af8965e8c4a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-0b2b1ba0f231a8b554f0afbce566f2ed</value>
      <webElementGuid>ad7283d1-866d-4c25-9dd3-fe8cc37c326b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-labelledby = ':r1j:']</value>
      <webElementGuid>564a9ca5-3922-4e7b-b5a4-6d78b423f3bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-labelledby = ':r1j:']</value>
      <webElementGuid>b9b89809-0a38-4ea1-ba77-493e16d22fd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and (text() = 'Yonex' or . = 'Yonex')]</value>
      <webElementGuid>4f2e1818-cd23-4066-9879-d1272eb149d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
