<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_8b5cf6</name>
   <tag></tag>
   <elementGuidId>37d82041-9c41-42f0-bd37-66d13a6fd8a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-testid = 'preset-color-5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[data-testid=&quot;preset-color-5&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;preset-color-5&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b2d48853-909c-4b19-ab60-a5dc660fa5a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-12 h-12 rounded-lg border-2 border-gray-200 hover:border-gray-400 transition-all duration-200 hover:scale-105</value>
      <webElementGuid>eabfe60f-a3c4-423c-b653-a428dc08ab77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>preset-color-5</value>
      <webElementGuid>02f0973a-417f-47f9-8989-e0e110b60503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>#8b5cf6</value>
      <webElementGuid>4bd92aba-c528-4a6c-8ae6-8ab6d0ff3538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>#8b5cf6</value>
      <webElementGuid>92e44301-8af7-4f7e-9565-a5a5f7ff2b02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-0a2dda880ce8288c070da2e3a31350fc</value>
      <webElementGuid>c6e970a3-7734-4683-986f-87fe2878ee8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-testid = 'preset-color-5']</value>
      <webElementGuid>b4f4a1bb-d1fd-4f4a-9d18-39f5d481082b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-testid = 'preset-color-5']</value>
      <webElementGuid>3fdaf406-4bd1-4556-b853-d1ff053e94ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@title = '#8b5cf6' and (text() = '#8b5cf6' or . = '#8b5cf6')]</value>
      <webElementGuid>a4bc412e-72b0-49b3-a965-62080a8d8e12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
