<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_000000</name>
   <tag></tag>
   <elementGuidId>de92c2fe-c953-47ee-8095-b769ac44b7ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-testid = 'hex-color-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[data-testid=&quot;hex-color-input&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;hex-color-input&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>56790ca6-5862-4c16-9c10-adf1eac2deea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>color-input</value>
      <webElementGuid>374adc1e-95b1-4c36-831d-7d050aeb9dba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>003648ff-68d5-4b0f-b1a9-a5444a37ceac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>#000000</value>
      <webElementGuid>11436ba4-91f2-48ab-b0c2-95fa4f33aea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full px-3 py-2 border rounded-md font-mono</value>
      <webElementGuid>37fbd26e-9a94-4ba8-9b8f-13118a76d9c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>hex-color-input</value>
      <webElementGuid>63a35aa9-d3e2-489f-91b8-12abc48fedd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>#3b82f6</value>
      <webElementGuid>12db4145-07bb-4155-bda8-1f440d3e0f30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>#000000</value>
      <webElementGuid>eba2b3b5-4429-42ba-bca7-6a4aa81c7041</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-161b32ed8ff143e106eee87eee7148e0</value>
      <webElementGuid>2705868e-dd0a-430e-b9a0-07a53e740bca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-testid = 'hex-color-input']</value>
      <webElementGuid>1ca2e50f-8b8e-4e84-acd0-8d08cd63a473</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-testid = 'hex-color-input']</value>
      <webElementGuid>13997356-14c6-42b3-a037-8bc1c6e2aa0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'color-input' and @type = 'text' and @placeholder = '#000000' and (text() = '#000000' or . = '#000000')]</value>
      <webElementGuid>119ff12f-76f5-4a18-880a-756b6c86c7ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
