<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Gii thiu v trang ny_a-1ru4utyy7x98</name>
   <tag></tag>
   <elementGuidId>ea93152d-2ae6-427f-bc3d-ee675462553d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-1ru4utyy7x98']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-1ru4utyy7x98&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;a-1ru4utyy7x98&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>be10e8c1-d5c1-4031-9af5-901858f44d69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>d4d1853d-1574-4267-accd-7b0d0c704d6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>dbe6a011-acde-43d9-83ec-4bf121179cbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>09f0e450-a392-415d-96ac-e956ca08bfb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>06b7c56d-3052-45d5-b895-51883d33ff1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-1ru4utyy7x98</value>
      <webElementGuid>89076a6e-3cfd-4005-bfaf-dbdcbfe237b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4e88e780-e60c-49a1-be95-0fce44efa456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>9f7ef447-0feb-451e-96d1-aedbea885425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>0c555158-ab2a-4be0-9ff5-b65113e27c27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/enterprise/anchor?ar=1&amp;k=6LdLLIMbAAAAAIl-KLj9p1ePhM-4LCCDbjtJLqRO&amp;co=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbTo0NDM.&amp;hl=en&amp;v=vUgXt_KV952_-5BB2jjloYzl&amp;size=normal&amp;s=K0udtJL0Gqi9Y2BIGTuvbp-CxXKLgT10rkncjSDI8-m4-60b-gBk7VjFfHXplF4mnTEc_kDvtaO_8Y0TO73XA9oCa9J5AhCJMOi85U7gCxCgX4KgfdiUP8hrxGTmbgSbJhJ9i7qir9mEmogRjyjoefHctS-AndtV44aUTMZTaXDGyCli1o8PCqYuc_3InyTHdP-cWQkJLQ8v4yMIb92iKO2uKksvC1jvD7wJ3H6m1AA1GF1EwVwjuk6qnwcB07ELGzNnrWsKVC8zY3qcf7Rh-FoYab5LsMk&amp;anchor-ms=20000&amp;execute-ms=30000&amp;cb=97zpc6w41kmw</value>
      <webElementGuid>a6d40802-b806-475a-af79-591b39a38da6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recaptcha&quot;)/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>bdb26dcd-a74d-480b-a567-8f69aac8ae1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-1ru4utyy7x98']</value>
      <webElementGuid>e8a99fab-67a1-41f5-a222-aac31b94cc64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='recaptcha']/div/div/iframe</value>
      <webElementGuid>8d95617f-2dd7-4ef2-b5e2-911e02884d72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>8874c596-3e77-4fdd-b52b-b8d90b1e434f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @name = 'a-1ru4utyy7x98' and @src = 'https://www.google.com/recaptcha/enterprise/anchor?ar=1&amp;k=6LdLLIMbAAAAAIl-KLj9p1ePhM-4LCCDbjtJLqRO&amp;co=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbTo0NDM.&amp;hl=en&amp;v=vUgXt_KV952_-5BB2jjloYzl&amp;size=normal&amp;s=K0udtJL0Gqi9Y2BIGTuvbp-CxXKLgT10rkncjSDI8-m4-60b-gBk7VjFfHXplF4mnTEc_kDvtaO_8Y0TO73XA9oCa9J5AhCJMOi85U7gCxCgX4KgfdiUP8hrxGTmbgSbJhJ9i7qir9mEmogRjyjoefHctS-AndtV44aUTMZTaXDGyCli1o8PCqYuc_3InyTHdP-cWQkJLQ8v4yMIb92iKO2uKksvC1jvD7wJ3H6m1AA1GF1EwVwjuk6qnwcB07ELGzNnrWsKVC8zY3qcf7Rh-FoYab5LsMk&amp;anchor-ms=20000&amp;execute-ms=30000&amp;cb=97zpc6w41kmw']</value>
      <webElementGuid>9e3d1590-3eb2-45dd-991e-f8a834016108</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
